// Generated by CoffeeScript 1.11.1
(function() {
  define(['angularAMD', 'angular', 'routes', 'angular-route'], function(angularAMD, angular, routes) {
    var $body, app, deps;
    deps = ['ngRoute'];
    app = angular.module('MoneyCompanion', deps);
    app.config(['$routeProvider', '$httpProvider', '$locationProvider', routes]);
    $body = angular.element(document);
    return angularAMD.bootstrap(app, true, $body);
  });

}).call(this);
