// Generated by CoffeeScript 1.11.1
(function() {
  define(['angularAMD'], function(angularAMD) {
    var routes;
    return routes = function($routeProvider, $httpProvider, $locationProvider) {
      $locationProvider.html5Mode(true);
      return $routeProvider.when("/", angularAMD.route({
        templateUrl: './views/home.html',
        controllerUrl: 'HomeController'
      })).otherwise({
        redirectTo: '/'
      });
    };
  });

}).call(this);
