// Generated by CoffeeScript 1.7.1
(function() {
  define(['interface'], function(__interface__) {
    var HomeController;
    HomeController = function($scope) {
      return console.log($scope);
    };
    return ['$scope', HomeController];
  });

}).call(this);
